version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
       - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
  gateway:
    image: qoomon/docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  cache:
    image: redis
    ports:
      - 6379:6379
  python-env:
    image: python:2.7.15
  python3-env:
    image: python:3.6.8
  node-env:
    image: node:10.15.0
  ruby-env:
    image: ruby:2.6.0
  sage-env:
    image: sagemath/sagemath
  cpp-compiler:
    build: ./compilers/cpp
    image: cpp-compiler
  csharp-compiler:
    build: ./compilers/csharp
    image: csharp-compiler
  java-compiler:
    build: ./compilers/java
    image: java-compiler
  rust-compiler:
    build: ./compilers/rust
    image: rust-compiler
