version: "3"
services:
  nginx:
    image: upstreamable/nginx-proxy:alpine-0.7.0
    ports:
      - "80:80"
      - 443:443
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-ssl:
    image: letsencrypt-nginx-proxy-companion:v1.10
    volumes:
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  cache:
    image: redis
    ports:
      - 6379:6379
  backend:
    image: jdis/platform-backend
    ports:
     - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/codes:/app/data/codes
    environment:
      - VIRTUAL_HOST=jdis-ia.dinf.usherbrooke.ca,localhost
      - VIRTUAL_PATH=/api
      - HOST_PWD=${PWD}
    depends_on:
      - nginx
      - database
      - cache
  frontend:
    image: jdis/platform-frontend
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=jdis-ia.dinf.usherbrooke.ca,localhost
      - VIRTUAL_PATH=/
    depends_on:
      - nginx
      - database
      - cache
  python-env:
    image: python:2.7.15
  python3-env:
    image: python:3.6.8
  node-env:
    image: node:10.15.0
  ruby-env:
    image: ruby:2.6.0
  sage-env:
    image: sagemath/sagemath
  cpp-compiler:
    build: ./compilers/cpp
    image: cpp-compiler
  csharp-compiler:
    build: ./compilers/csharp
    image: csharp-compiler
  java-compiler:
    build: ./compilers/java
    image: java-compiler
  rust-compiler:
    build: ./compilers/rust
    image: rust-compiler
  haskell-compiler:
    build: ./compilers/haskell
    image: haskell-compiler
  fsharp-compiler:
    build: ./compilers/fsharp
    image: fsharp-compiler
